export const data = [
  {
    id: 1,
    categorie: "Data Base & web",
    title: "Visual studio code",
    pic: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Visual_Studio_Code_1.35_icon.svg/1200px-Visual_Studio_Code_1.35_icon.svg.png",
    paragraph: "",
    link: "",
  },
  {
    id: 2,
    categorie: "Programming & algorithm",
    title: "Thonny",
    pic: "https://images.sftcdn.net/images/t_app-icon-m/p/b7c6837f-d3d8-48a2-985a-aae1988e1ac3/524712048/thonny-Thonny-icon.png",
    paragraph: "",
    link: "",
  },
  {
    id: 3,
    categorie: "Data Base & web",
    title: "Sublime text",
    pic: "https://upload.wikimedia.org/wikipedia/fr/7/78/Sublime_text_logo.png",
    paragraph: "",
    link: "",
  },
  {
    id: 4,
    categorie: "Data Base & web",
    title: "Sqlite",
    pic: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/SQLite370.svg/2560px-SQLite370.svg.png",
    paragraph: "",
    link: "",
  },
  {
    id: 5,
    categorie: "Programming & algorithm",
    title: "Qt designer",
    pic: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Qt_small.svg/965px-Qt_small.svg.png",
    paragraph: "",
    link: "",
  },
  {
    id: 6,
    categorie: "Data Base & web",
    title: "Blue Griffon",
    pic: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Faenza-bluegriffon.svg/langfr-220px-Faenza-bluegriffon.svg.png",
    paragraph: "",
    link: "",
  },
];
